name = "url-keep-api"
main = "src/index.ts"
compatibility_date = "2026-03-09"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_ORIGIN = "https://www.url-keep.com,https://url-keep.com"
DEBUG_LOGS = "1"
NARRATION_SERVICE_ORIGIN = "https://api.wavey.info/api/narration"

ALLOWED_EXTENSION_ORIGINS = "chrome-extension://pgldbhelglnjpgdmjhciahkcehmoopif"

[[d1_databases]]
binding = "DB"
database_name = "url_keep"
database_id = "a1b37e64-4972-4dae-bfd9-a0fe8beb91f3"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "url-keep-images"

[[routes]]
pattern = "api.url-keep.com"
custom_domain = true
